[package]
name = "rust-hashmap-lookup-bench"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dev-dependencies]
criterion = { version = "*", default-features = false, features = [] }
rand = "*"

[[bench]]
name = "benchmark"
harness = false
