name: CI

on: push

jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Install cargo wasi
      run: cargo install cargo-wasi
    - name: Show rust version
      run: rustc --version
    - name: Setup homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install wasmtime and wasmer
      run: brew install wasmtime wasmer
    - name: Run benchmarks
      run: ./run-bench.sh
